name: Build All Wheels

on:
  workflow_dispatch: # 手动触发
  push:
    paths:
      - requirements.txt # 当requirements.txt变化时自动触发

jobs:
  build-wheels:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.13"] # 可扩展其他版本
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup MSVC Build Tools
      uses: ilammy/setup-msvc@v1 # 自动配置C++编译环境
    
    - name: Install system libraries
      run: |
        choco install -y libjpeg-turbo zlib # 按需添加系统依赖
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools cython
    
    - name: Build all wheels
      run: |
        mkdir dist
        pip wheel \
          --wheel-dir dist \
          --no-cache-dir \
          --no-binary :all: \ # 强制从源码构建所有包
          -r requirements.txt
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-wheels-${{ matrix.python-version }}
        path: dist/
        